### ISSUE TITLE
Cut point of short/long seq kernels

### ISSUE THREAD

**Issue by qingchanghan** [bytedance/ByteTransformer#2]
The paper said: "we set 384 to be the cut-off sequence length and propose a grouped GEMM based fused MHA for large models."

And the cut point is seemly 80 in the code. Have long sequence kernels better performance than short sequence kernels for seq in 80~384 length?

**Comment by kongroo** [comment]
In fact, the cut point in the code is 128 (for A100).
 
The fused kernel is faster for <= 384 seqlen. I have updated the code.

**Comment by qingchanghan** [comment]
Thank you for your reply!

Sorry and I think I misunderstood. And here is the 80 I mentioned. (https://github.com/bytedance/ByteTransformer/blob/main/bytetransformer/include/attention.h#L126)

For fused kernel, if seq_len < 80, we can load a whole `seq_len`x`size_per_head` tile to shared memory, so we don't need split `seq_len`. Is that right?

**Comment by kongroo** [comment]
Yes, the cut point of fused kernel is due to shared memory limit.
