### ISSUE TITLE
Header including error

### ISSUE THREAD

**Issue by aska-0096** [bytedance/ByteTransformer#3]
Board: A100 PCIE
Docker: pytorch/pytorch:1.13.0-cuda11.6-cudnn8-devel
Command: 
1. git clone --recursive https://github.com/bytedance/ByteTransformer.git
2. mkdir build && cd build
3. cmake -DDataType=FP16 -DBUILD_THS=ON -DCUDAARCHS="80" ..
4. make

Error info:

[  5%] Building CUDA object bytetransformer/src/CMakeFiles/bytetransformer.dir/bert_transformer.cu.o
In file included from /root/workspace/ByteTransformer/bytetransformer/include/bert_transformer.h:25:0,
                 from /root/workspace/ByteTransformer/bytetransformer/src/bert_transformer.cu:20:
/root/workspace/ByteTransformer/bytetransformer/include/cutlass_attention.h:28:10: fatal error: cutlass/util/device_memory.h: No such file or directory
 #include "cutlass/util/device_memory.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
bytetransformer/src/CMakeFiles/bytetransformer.dir/build.make:187: recipe for target 'bytetransformer/src/CMakeFiles/bytetransformer.dir/bert_transformer.cu.o' failed
make[2]: *** [bytetransformer/src/CMakeFiles/bytetransformer.dir/bert_transformer.cu.o] Error 1
CMakeFiles/Makefile2:150: recipe for target 'bytetransformer/src/CMakeFiles/bytetransformer.dir/all' failed
make[1]: *** [bytetransformer/src/CMakeFiles/bytetransformer.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2

Is cutlass submodule need to be update?

**Comment by aska-0096** [comment]
in another docker nvcr.io/nvidia/pytorch:23.02-py3, I got following error:

/root/workspace/ByteTransformer/cutlass_contrib/include/cutlass/contrib/gemm/threadblock/default_mma.h:50:10: fatal error: cutlass/contrib/gemm/threadblock/mma_singlestage.h: No such file or directory
   50 | #include "cutlass/contrib/gemm/threadblock/mma_singlestage.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by yzhaiustc** [comment]
1. seemingly the CMakeLists does not include the path containing `device_memory.h`
Its full path is `ByteTransformer/3rdparty/cutlass/tools/util/include/cutlass/util/device_memory.h`
A solution may be to include `ByteTransformer/3rdparty/cutlass/tools/util/include/` in cmake.

2. `mma_singlestage` is not needed under this hardcoded config: https://github.com/bytedance/ByteTransformer/blob/main/bytetransformer/include/cutlass_attention_defs.h#L46-L47
You may just remove this line of code.

Would you please update the code some time? Thanks a lot. @kongroo

**Comment by aska-0096** [comment]
Thanks @yzhaiustc 
Solve the including error based on your advice, btw, I remove the following two lines:
https://github.com/bytedance/ByteTransformer/blob/c12eb288b206df53a743d60753d250c32f022cf1/cutlass_contrib/include/cutlass/contrib/gemm/threadblock/default_mma.h#L50-L51

and it seems we'd better add -DCUDA_PATH=/usr/local/cuda option to cmake command

**Comment by aska-0096** [comment]
I passed the benchmark and test, would you mind me create a PR to help you fix this error?

**Comment by yzhaiustc** [comment]
Thanks. Glad to see it works.
I'm outside ByteDance so please check with the maintainer regarding PRs.

**Comment by kongroo** [comment]
> 1. seemingly the CMakeLists does not include the path containing `device_memory.h`
>    Its full path is `ByteTransformer/3rdparty/cutlass/tools/util/include/cutlass/util/device_memory.h`
>    A solution may be to include `ByteTransformer/3rdparty/cutlass/tools/util/include/` in cmake.
> 2. `mma_singlestage` is not needed under this hardcoded config: https://github.com/bytedance/ByteTransformer/blob/main/bytetransformer/include/cutlass_attention_defs.h#L46-L47
>    You may just remove this line of code.
> 
> Would you please update the code some time? Thanks a lot. @kongroo

I have fixed this issue. 1. remove the two lines of including non-existing headers; 2. add missing header and lib paths. @aska-0096 @yzhaiustc

**Comment by aska-0096** [comment]
Good.
I think I can close the PR & issue
