### ISSUE TITLE
linking error: /usr/bin/x86_64-linux-gnu-ld: cannot find -lmkl_intel_ilp64

### ISSUE THREAD

**Issue by LHengyi** [bytedance/ByteTransformer#8]
Hi, I follow the README file to build this project,
I'm using:
  Ubuntu 18.04.6 LTS
  cuda 11.7
  python 3.8.0
  g++-6
  torch 2.0.1+cu117
I ran
`cmake -DTORCH_CUDA_ARCH_LIST="8.0" -DDataType=FP16 -DBUILD_THS=ON -DCUDAARCHS="80"  ..`
then make.

I encounter the following error:

> Consolidate compiler generated dependencies of target bytetransformer
[ 66%] Built target bytetransformer
Consolidate compiler generated dependencies of target ths_bytetransformer
[ 72%] Linking CXX shared library ../../lib/libths_bytetransformer.so
/usr/bin/x86_64-linux-gnu-ld: cannot find -lmkl_intel_ilp64
/usr/bin/x86_64-linux-gnu-ld: cannot find -lmkl_core
/usr/bin/x86_64-linux-gnu-ld: cannot find -lmkl_intel_thread
collect2: error: ld returned 1 exit status
bytetransformer/th_op/CMakeFiles/ths_bytetransformer.dir/build.make:166: recipe for target 'lib/libths_bytetransformer.so' failed
make[2]: *** [lib/libths_bytetransformer.so] Error 1
CMakeFiles/Makefile2:176: recipe for target 'bytetransformer/th_op/CMakeFiles/ths_bytetransformer.dir/all' failed
make[1]: *** [bytetransformer/th_op/CMakeFiles/ths_bytetransformer.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2

I check the CMakeLists files, but I can't find anything linked to mkl libraries. Any clue on this?

**Comment by yzhaiustc** [comment]
It looks that Intel MKL wasn't correctly configured in your system.
Would you please try to built on docker `nvcr.io/nvidia/pytorch:23.05-py3` ?
I tested the building and things went well in this docker.

**Comment by LHengyi** [comment]
> It looks that Intel MKL wasn't correctly configured in your system. Would you please try to built on docker `nvcr.io/nvidia/pytorch:23.05-py3` ? I tested the building and things went well in this docker.

Thanks, Yujia. An alternative is to run the setvars.sh scripts. In my case:
`source /opt/intel/oneapi/setvars.sh --force intel64 mod`
